FROM node:20.9.0 As builder
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn config set disable-self-update-check true
COPY . .
RUN rm -r ./node_modules
RUN yarn install
RUN yarn build

FROM node:20.9.0 As runner
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist/src ./dist
COPY --from=builder /usr/src/app/.env.docker ./.env

EXPOSE 3001
CMD yarn start:prod