services:
  api:
    build: 
      dockerfile: DockerFile
      context: .
    depends_on:
      - app_mongo
    env_file:
      - .env.docker
    ports:
      - 3002:3001
    volumes:
      - .:/app
      
  app_mongo:
    image: mongo:latest
    ports:
      - 27117:27017
    volumes:
      - app_mongo:/var/lib/mongo
  
volumes:
  app_mongo:
    driver: local